parameters:
    clearcode_urler.generator.simple.class: Clearcode\UrlerBundle\Generator\SimpleTokenGenerator

services:
    clearcode_urler.generator.simple:
        class: %clearcode_urler.generator.simple.class%
        arguments: [ @doctrine.orm.entity_manager ]

    clearcode_urler.shortener:
        class: Clearcode\UrlerBundle\Services\ShortenerService
        arguments: [ @clearcode_urler.generator.simple ]