<?php

namespace Clearcode\UrlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlGalleryRepository extends EntityRepository
{
}
