<?php

namespace Clearcode\UrlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UrlGalleryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlGalleryItemRepository extends EntityRepository
{
}
